apiVersion: v1
kind: Secret
metadata:
  name: microocpp-secret
type: Opaque
data:
  DB_CONNECTION_URL: <base64-encoded-value>
  STATUS_CHANGE_WEBHOOK_URL: <base64-encoded-value>
  TRANSACTION_COMPLETION_WEBHOOK_URL: <base64-encoded-value>
